### ISSUE TITLE
跑起来效果不行

### ISSUE THREAD

**Issue by dz-star** [CyberAgentAILab/TANGO#32]
跑起来效果不行，跟demo效果差很远，唇形都对不好，什么原因？

**Comment by H-Liu1997** [comment]
hi 可以上传你的结果具体看下不
- 唇形 我们用的开源wav2lip，如果你觉得不准，你可以替换成其他开源项目比如wav2lip-hd，或者商用项目。
- 这个项目主要是在唇形的基础上，同步肢体动作，如果你认为肢体动作有很大问题，我们看看问题在哪

**Comment by dz-star** [comment]
感谢回复！请帮忙看看！

https://github.com/user-attachments/assets/038f04c4-7786-441e-bde7-124592f81587

**Comment by H-Liu1997** [comment]
0-3s 没说话的时候是有问题，因为我们设计的时候没考虑 沉默的处理。
3-17s 是正常的结果，肢体动作还是同步的，如果是分辨率问题 以及想如果追求更高精度的lipsync，请参考 #1

**Comment by dz-star** [comment]
好，多谢！
