### ISSUE TITLE
create_graph error

### ISSUE THREAD

**Issue by luffy-git** [CyberAgentAILab/TANGO#35]
FileNotFoundError: [Errno 2] No such file or directory: '/data/TANGO/outputs/save_video.json'

![image](https://github.com/user-attachments/assets/8bb85aa8-94cb-4883-bfa1-cd34f243f225)

**Comment by luffy-git** [comment]
fix  :  pip install numpy==1.23.5

**Comment by HiouKaoru-3** [comment]
你好，我想问下怎么获得create_graph.py所需要的输入数据，我没有找到相关代码
