### ISSUE TITLE
变得好丑啊~~

### ISSUE THREAD

**Issue by gg22mm** [CyberAgentAILab/TANGO#9]
变得好丑啊~~：~~

![图片](https://github.com/user-attachments/assets/244788cf-9c6e-4ffb-baf5-76f2761a4fd4)

**Comment by H-Liu1997** [comment]
口型我们用的开源的wav2lip，这个项目是生成身体动作的。如果不满意请自己替换其他对口型算法在app.py 

https://github.com/CyberAgentAILab/TANGO/blob/e24a2f4c64f4e9addb57aad1ebb8cdaf2eeada6c/app.py#L384
